import type { ThermalShaderConfig, ThermalShaderPresetId } from './types'

export const THERMAL_SHADER_PRESETS: Record<ThermalShaderPresetId, ThermalShaderConfig> = {
  cotton: {
    opacityBase: 0.16,
    speedMin: 0.5,
    speedMax: 1.15,
    flowDirection: -1,
    ascentBoost: 1.25,
    noiseScale: 3.4,
    edgeSoftness: 0.35,
    bandCount: 10,
    colorLow: '#88dcff',
    colorHigh: '#ffffff',
    stripeFrequency: 30,
    stripeWidth: 0.18,
    stripeContrast: 0.38,
    wobbleFrequency: 11,
    wobbleAmplitude: 0.28,
    rimBoost: 0.18,
    alphaBoost: 0.2,
  },
  spiral: {
    opacityBase: 0.15,
    speedMin: 0.1,
    speedMax: 3.2,
    flowDirection: -1,
    ascentBoost: 0.5,
    noiseScale: 12,
    edgeSoftness: 0.5,
    bandCount: 5,
    colorLow: '#2b3f52',
    colorHigh: '#f7fcff',
    stripeFrequency: 8,
    stripeWidth: 0.08,
    stripeContrast: 0.9,
    wobbleFrequency: 32,
    wobbleAmplitude: 0.9,
    rimBoost: 0.05,
    alphaBoost: 0.12,
  },
  plasma: {
    opacityBase: 0.24,
    speedMin: 0.85,
    speedMax: 2.1,
    flowDirection: -1,
    ascentBoost: 1.95,
    noiseScale: 6.6,
    edgeSoftness: 0.26,
    bandCount: 12,
    colorLow: '#43b8ff',
    colorHigh: '#ffffff',
    stripeFrequency: 54,
    stripeWidth: 0.1,
    stripeContrast: 0.68,
    wobbleFrequency: 20,
    wobbleAmplitude: 0.56,
    rimBoost: 0.33,
    alphaBoost: 0.4,
  },
}

export const DEFAULT_THERMAL_SHADER_PRESET: ThermalShaderPresetId = 'spiral'
